name: CI
on:
  push:
    branches: 
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: sa-east-1

jobs:
  build:
    name: "Build and Test Functions"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      working-directory: ./src/DotLancheAuthentication/DotLancheAuthentication  # Corrigir o caminho
      run: dotnet restore

    - id: build_functions
      name: Build Functions
      working-directory: ./src/DotLancheAuthentication/DotLancheAuthentication  # Corrigir o caminho
      run: dotnet build --no-restore

  validate:
    name: "Terraform Validate"
    defaults:
      run:
        shell: bash
        working-directory: ./infra/
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - id: init
      name: Terraform Init
      run: terraform init -backend-config="bucket=${{ vars.TERRAFORM_S3_BACKEND }}"

    - id: validate
      name: Terraform Validate
      run: terraform validate