name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init -backend-config="bucket=lanchesjaamp-sa-east-1-terraform-statefile" -backend-config="region=sa-east-1"

    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan -out=tfplan -var-file="./envs/prod/terraform.tfvars"

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve tfplan

  package:
    name: "Package and Deploy Code"
    runs-on: ubuntu-latest
    needs: terraform  # Executa apenas após o job "terraform" ser bem-sucedido

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Build
      working-directory: ./src/DotLancheAuthentication/DotLancheAuthentication
      run: dotnet build -c release

    - name: Generate Lambda ZIP
      working-directory: ./src/DotLancheAuthentication/DotLancheAuthentication
      run: dotnet lambda package --output-package ../../../infra/v${{ github.run_id }}.zip

    - name: Terraform Init for Code Deploy
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init (for Code Deploy)
      working-directory: ./infra
      run: terraform init -backend-config="bucket=lanchesjaamp-sa-east-1-terraform-statefile" -backend-config="region=sa-east-1"

    - name: Terraform Plan (Code Deploy)
      working-directory: ./infra
      env: 
        TF_VAR_zip_file: v${{ github.run_id }}.zip
        TF_VAR_functions_role: "arn:aws:iam::943457664629:role/lambda-execution-role"
      run: terraform plan -var "zip_file=v${{ github.run_id }}.zip" -var "functions_role=arn:aws:iam::943457664629:role/lambda-execution-role"

    - name: Terraform Apply (Code Deploy)
      working-directory: ./infra
      env: 
        TF_VAR_zip_file: v${{ github.run_id }}.zip
        TF_VAR_functions_role: "arn:aws:iam::943457664629:role/lambda-execution-role"
      run: terraform apply -auto-approve -var "zip_file=v${{ github.run_id }}.zip" -var "functions_role=arn:aws:iam::943457664629:role/lambda-execution-role"
