name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Deploy Infrastructure"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - name: Terraform Init
      working-directory: ./infra
      run: terraform init -backend-config="bucket=lanchesjaamp-sa-east-1-terraform-statefile" -backend-config="region=sa-east-1"

    - name: Terraform Plan
      working-directory: ./infra
      run: terraform plan -out=tfplan -var-file="./envs/prod/terraform.tfvars"

    - name: Terraform Apply
      working-directory: ./infra
      run: terraform apply -auto-approve tfplan