name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::943457664629:role/github-actions-dotlanche-pipeline"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "lanchesjaamp-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "lanchesjaamp-sa-east-1-terraform-lock"

  package:
    name: "Package functions and Deploy Terraform"
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Lambda Tools
      run: dotnet tool install -g Amazon.Lambda.Tools

    - name: Build
      working-directory: ./src/DotLancheAuthentication/DotLancheAuthentication
      run: dotnet build -c release

    - name: Generate Lambdas ZIP
      working-directory: ./src/DotLancheAuthentication/DotLancheAuthentication
      run: dotnet lambda package --output-package ../../../infra/v${{ github.run_id }}.zip

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    - id: init
      name: Terraform Init
      working-directory: ./infra
      run: terraform init -backend-config="bucket=lanchesjaamp-sa-east-1-terraform-statefile" -backend-config="region=sa-east-1"

    - id: plan
      name: Terraform Plan
      working-directory: ./infra
      env: 
        TF_VAR_zip_file: v${{ github.run_id }}.zip
        TF_VAR_functions_role: "arn:aws:iam::943457664629:role/lambda-execution-role"  # Substitua por um ARN de role existente
      run: terraform plan -var "zip_file=v${{ github.run_id }}.zip" -var "functions_role=arn:aws:iam::943457664629:role/lambda-execution-role"

    - id: apply
      name: Terraform Apply
      working-directory: ./infra
      env: 
        TF_VAR_zip_file: v${{ github.run_id }}.zip
        TF_VAR_functions_role: "arn:aws:iam::943457664629:role/lambda-execution-role"  # Substitua por um ARN de role existente
      run: terraform apply -auto-approve -var "zip_file=v${{ github.run_id }}.zip" -var "functions_role=arn:aws:iam::943457664629:role/lambda-execution-role"
